steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - main
  - --region=asia-northeast1
  - --source=.
  - --trigger-topic=<TOPIC_NAME>
  - --runtime=python39