steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - main
  - --region=asia-northeast1
  - --source=.
  - --trigger-topic=<TOPIC_NAME>
  - --runtime=python39
  - --set-secrets=/application/src/google-credential.json=projects/79432760668/secrets/my-secrets/versions/2